version: '3'

services:
  rpcc-postgres:
    image: postgres:15.5-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - rpcc-postgres-data:/var/lib/postgresql/data
    networks:
      - rpcc-network

  rpcc-backend:
    build:
      context: Backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - rpcc-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rpcc-postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - rpcc-network

volumes:
  rpcc-postgres-data:

networks:
  rpcc-network:
    driver: bridge
