version: '3'

services:
  risdnz-postgres:
    image: postgres:15.5-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - risdnz-postgres-data:/var/lib/postg
    networks:
      - risdnz-networkresql/data
      

  risdnz-backend:
    build:
      context: Backend
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - risdnz-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://risdnz-postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - risdnz-network

volumes:
  risdnz-postgres-data:

networks:
  risdnz-network:
    driver: bridge
