version: '3'

services:
  postgres:
    image: postgres:15.5-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bazepodataka
      POSTGRES_DB: rpcc
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: Backend
    depends_on:
      - postgres
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rpcc
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: bazepodataka

  frontend:
    build:
      context: Frontend
    depends_on:
      - backend
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro

  ssl-service:
    image: certbot/certbot:v2.6.0
    depends_on:
      - frontend
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command:
#      - certonly
#      - --webroot
#      - -w
#      - /var/www/certbot/
#      - --email=gjino@ur-institute.org
#      - --agree-tos
#      - --no-eff-email
#      - -d
#      - restorativepractices.xyz
      - renew

volumes:
  postgres-data:

